[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "aware garage lizard illegal vessel fetch near frost angle air crater try eternal since tuna wave lecture degree melt tunnel dinosaur isolate shrimp divide"
